# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2c5dfed02337fd4e615b45b46186225874c8c57acc969534e17dc8c91d0719e9996c8e062d96a57fefa908aa36e764bde1dc4feb92f668aa1cdeef22fa13fff

test:
  secret_key_base: 4dac53540bfebcbbdf0ffc1ba7c453885cf522bd5a403eed3c085380e71359404dd7c1fc3641d0299753444c2038e560aef1bb470264f6f6f57835f51c7e1135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
